# Generated by Django 5.2.4 on 2025-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
