# Generated by Django 5.2.4 on 2025-07-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_alter_brand_name_alter_vehicle_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviços',
            },
        ),
        migrations.CreateModel(
            name='Maintenances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando aprovação'), ('in_progress', 'Em andamento'), ('completed', 'Concluído')], max_length=100, verbose_name='Status')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_maintenances', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('maintenances', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='maintenances.maintenances', verbose_name='Manutenção')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_type', to='maintenances.servicetype', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='maintenances',
            new_name='maintenance',
        ),
    ]
