# Generated by Django 5.2.4 on 2025-07-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='maintenance',
            new_name='maintenances',
        ),
    ]
