# Generated by Django 5.2.4 on 2025-07-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0002_rename_maintenance_service_maintenances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='maintenances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenances.maintenances', verbose_name='Manutenção'),
        ),
    ]
