# Generated by Django 5.2.4 on 2025-07-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenances', '0003_alter_service_maintenances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenances',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
